CREATE TABLE IF NOT EXISTS posts
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    name VARCHAR(255)                            NOT NULL,
    text VARCHAR(2550)                           NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);